include:
  - compose-deps.yaml

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /app
    stop_grace_period: 100ms
    networks:
      - app-network
    depends_on:
      trickle:
        condition: service_started
      firehose:
        condition: service_started
      webhooks:
        condition: service_healthy
