#!/bin/sh
set -eu

# Spins up a small zoo of noisy containers to point dolog at:
#
#   compose project "dolog-zoo"  gateway / checkout / payments   -- exercises container grouping
#   dolog-cron                   standalone, ungrouped           -- exercises the no-group path
#   dolog-firehose               ~thousands of lines per second  -- exercises the throttler
#   dolog-flapper                dies every 15s and restarts     -- exercises start/stop events
#
# "payments" writes to stderr, everything else to stdout.

COMPOSE_FILE="compose-containers.yaml"
COMPOSE_PROJECT="dolog-zoo"
STANDALONE="dolog-cron dolog-firehose dolog-flapper"

usage() {
    printf "Usage: %s <up|down|status>\n" "$(basename "$0")"
    exit 1
}

require_commands() {
    for cmd in "$@"; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            printf "Error: required command not found: %s\n" "$cmd"
            exit 1
        fi
    done
}

# Emits a plausible-looking access log line every $1 seconds, on stdout unless $2 is "stderr".
# Deterministic rather than random, so the output stays reproducible between runs.
chatter() {
    _interval="$1"
    _redirect=""
    if [ "${2:-stdout}" = "stderr" ]; then
        _redirect=" >&2"
    fi
    cat <<CHATTER
i=0
while true; do
  i=\$((i + 1))
  case \$((i % 6)) in
    0) m=GET;    p=/ ;;
    1) m=GET;    p=/health ;;
    2) m=POST;   p=/api/orders ;;
    3) m=GET;    p=/api/orders/8821 ;;
    4) m=PUT;    p=/assets/app.css ;;
    *) m=DELETE; p=/login ;;
  esac
  case \$(((i * 3) % 10)) in
    0|1|2|3|4) c=200 ;;
    5) c=201 ;;
    6) c=304 ;;
    7) c=404 ;;
    8) c=500 ;;
    *) c=200 ;;
  esac
  echo "\$(date -u +%H:%M:%S) \"\$m \$p\" \$c \$(((i * 37) % 400 + 3))ms"$_redirect
  sleep $_interval
done
CHATTER
}

# docker compose expands \$ in the file itself, so every shell \$ has to be doubled.
chatter_for_compose() {
    chatter "$@" | sed 's/\$/$$/g' | sed 's/^/          /'
}

write_compose_file() {
    {
        printf '# Generated by containers.sh -- do not edit, it is rewritten on every "up".\n'
        printf 'services:\n'
        for service in gateway:1:stdout checkout:2:stdout payments:3:stderr; do
            name=$(echo "$service" | cut -d: -f1)
            interval=$(echo "$service" | cut -d: -f2)
            stream=$(echo "$service" | cut -d: -f3)
            printf '  %s:\n' "$name"
            printf '    image: alpine\n'
            printf '    restart: unless-stopped\n'
            printf '    command:\n'
            printf '      - sh\n'
            printf '      - -c\n'
            printf '      - |\n'
            chatter_for_compose "$interval" "$stream"
        done
    } > "$COMPOSE_FILE"
}

cmd_up() {
    write_compose_file
    printf "Starting compose project '%s'\n" "$COMPOSE_PROJECT"
    docker compose -p "$COMPOSE_PROJECT" -f "$COMPOSE_FILE" up -d

    printf "Starting standalone containers\n"
    for name in $STANDALONE; do
        docker rm -f "$name" >/dev/null 2>&1 || true
    done

    docker run -d --name dolog-cron --restart unless-stopped alpine \
        sh -c "$(chatter 1 stdout)" >/dev/null

    # ~400 lines/second: comfortably over the default budget of 100, so the throttler has to fold
    # it, but bursty rather than a flat-out spin loop that pins a CPU core
    docker run -d --name dolog-firehose --restart unless-stopped alpine \
        sh -c 'i=0; while true; do j=0; while [ $j -lt 200 ]; do i=$((i + 1)); j=$((j + 1)); echo "burst line $i"; done; sleep 0.5; done' >/dev/null

    # Exits every 15 seconds and is restarted, so start/stop events keep arriving
    docker run -d --name dolog-flapper --restart unless-stopped alpine \
        sh -c 'echo "flapper up"; sleep 15; echo "flapper going down" >&2; exit 1' >/dev/null

    printf '\n'
    cmd_status
    printf '\nTear it all down again with: ./containers.sh down\n'
}

cmd_down() {
    if [ -f "$COMPOSE_FILE" ]; then
        docker compose -p "$COMPOSE_PROJECT" -f "$COMPOSE_FILE" down --remove-orphans >/dev/null 2>&1 || true
        rm -f "$COMPOSE_FILE"
    fi
    for name in $STANDALONE; do
        docker rm -f "$name" >/dev/null 2>&1 || true
    done
    printf "Removed the container zoo\n"
}

cmd_status() {
    printf 'Running:\n'
    docker ps --filter "label=com.docker.compose.project=$COMPOSE_PROJECT" --format '  {{.Names}} ({{.Status}})'
    for name in $STANDALONE; do
        docker ps --filter "name=^/$name$" --format '  {{.Names}} ({{.Status}})'
    done
}

require_commands docker

[ $# -ge 1 ] || usage

case "$1" in
    up) cmd_up ;;
    down) cmd_down ;;
    status) cmd_status ;;
    *) usage ;;
esac
